units:
  choc_cap_x: 17.5
  choc_cap_y: 16.5
  stagger_ring: cy
  stagger_middle: 3
  stagger_index: -6
  stagger_index2: -3
  slider_offset: 3
  smdbutton_offset_xR: 'cx/2-1'
  smdbutton_offset_y: -1.5
  nnano_offset: -10.5
  diode_x: 3.6
  diode_y: -2.6
  jst5offset: 8
  cxR: cx
  pinky_cutR: '2-cx'
  logoxR: -2.5
points:  
  key:
    padding: cy
    spread: cx
  zones:
    main:
      rows:
        bottom:
        home:
        top:
      columns:
        pinky:
          rows:
            bottom:
            home:
            top:
            ttop:
        ring:
          key:
            stagger: stagger_ring
        middle:
          key:
            stagger: stagger_middle
        index:
          key:
            stagger: stagger_index
        index2:
          key:
            stagger: stagger_index2    
          
outlines:
  switch_cutouts:
    - what: rectangle
      where: true
      asym: source
      size: 14 # Plate cutouts are 14mm * 14mm for both MX and Choc
      bound: false
  keycaps:
    - what: rectangle
      where: true
      asym: source
      size: [choc_cap_x,choc_cap_y]
      bound: false
  _bottom_ext:
    - what: rectangle
      where: 
        ref: main_middle_bottom
        shift: [0,stagger_index+stagger_index2]
      size: [cx*3,cy]  
  _pinky_cut:
    - what: rectangle
      where:
        ref: main_pinky_home
        shift: [pinky_cutR,0]
      size: [cx,100]  
  _perimeter:
    - what: rectangle
      where: true
      asym: source
      size: [cx+4,cy]
  _pcb_outline_raw: [      
      _perimeter,      
      _bottom_ext,      
      -_pinky_cut,  
  ]          
  pcb_edgecut:
    - what: outline
      name: _pcb_outline_raw
      fillet: 1.4992  
  preview: [      
    pcb_edgecut,    
    -switch_cutouts,  
    #-keycaps,    
  ] 

pcbs:
  left:
    outlines:
      main_outline:
        outline: pcb_edgecut
        layer: Edge.Cuts
      preview:
        outline: preview
        layer: Eco1.User
      keycaps:
        outline: keycaps
        layer: Eco2.User
    footprints:
      C0R0:
        what: f_new_choc
        where: 
          ref: main_pinky_top
          rotate: 180
        params:
          from: C0
          to: C0R0D
          label: C0R0
      C0R0diode:
        what: f_diode
        where: 
          ref: main_pinky_top
          shift: [-diode_x,-diode_y]
          rotate: 180
        params:
          from: C0R0D
          to: R0
      C0R1:
        what: f_new_choc
        where: 
          ref: main_pinky_home
          rotate: 180
        params:
          from: C0
          to: C0R1D
          label: C0R1
      C0R1diode:
        what: f_diode
        where: 
          ref: main_pinky_home
          shift: [-diode_x,-diode_y]
          rotate: 180
        params:
          from: C0R1D
          to: R1
      C0R2:
        what: f_new_choc
        where: 
          ref: main_pinky_bottom
          rotate: 180
        params:
          from: C0
          to: C0R2D
          label: C0R2
      C0R2diode:
        what: f_diode
        where: 
          ref: main_pinky_bottom
          shift: [-diode_x,-diode_y]
          rotate: 180
        params:
          from: C0R2D
          to: R2
      C1R0:
        what: f_new_choc
        where: 
          ref: main_ring_top
          rotate: 180
        params:
          from: C1
          to: C1R0D
          label: C1R0
      C1R0diode:
        what: f_diode
        where: 
          ref: main_ring_top
          shift: [-diode_x,-diode_y]
          rotate: 180
        params:
          from: C1R0D
          to: R0
      C1R1:
        what: f_new_choc
        where: 
          ref: main_ring_home
          rotate: 180
        params:
          from: C1
          to: C1R1D
          label: C1R1
      C1R1diode:
        what: f_diode
        where: 
          ref: main_ring_home
          shift: [-diode_x,-diode_y]
          rotate: 180
        params:
          from: C1R1D
          to: R1
      C1R2:
        what: f_new_choc
        where: 
          ref: main_ring_bottom
          rotate: 180
        params:
          from: C1
          to: C1R2D
          label: C1R2
      C1R2diode:
        what: f_diode
        where: 
          ref: main_ring_bottom
          shift: [-diode_x,-diode_y]
          rotate: 180
        params:
          from: C1R2D
          to: R2
      C2R0:
        what: f_new_choc
        where: 
          ref: main_middle_top
        params:
          from: C2
          to: C2R0D
          label: C2R0
      C2R0diode:
        what: f_diode
        where: 
          ref: main_middle_top
          shift: [diode_x,diode_y]
        params:
          from: C2R0D
          to: R0
      C2R1:
        what: f_new_choc
        where: 
          ref: main_middle_home
          rotate: 180
        params:
          from: C2
          to: C2R1D
          label: C2R1
      C2R1diode:
        what: f_diode
        where: 
          ref: main_middle_home
          shift: [-diode_x,-diode_y]
          rotate: 180
        params:
          from: C2R1D
          to: R1
      C2R2:
        what: f_new_choc
        where: 
          ref: main_middle_bottom
          rotate: 180
        params:
          from: C2
          to: C2R2D
          label: C2R2
      C2R2diode:
        what: f_diode
        where: 
          ref: main_middle_bottom
          shift: [-diode_x,-diode_y]
          rotate: 180
        params:
          from: C2R2D
          to: R2
      C3R0:
        what: f_new_choc
        where: 
          ref: main_index_top
        params:
          from: C3
          to: C3R0D
          label: C3R0
      C3R0diode:
        what: f_diode
        where: 
          ref: main_index_top
          shift: [diode_x,diode_y]
        params:
          from: C3R0D
          to: R0
      C3R1:
        what: f_new_choc
        where: 
          ref: main_index_home          
        params:
          from: C3
          to: C3R1D
          label: C3R1
      C3R1diode:
        what: f_diode
        where: 
          ref: main_index_home
          shift: [diode_x,diode_y]          
        params:
          from: C3R1D
          to: R1
      C3R2:
        what: f_new_choc
        where: 
          ref: main_index_bottom
          rotate: 180
        params:
          from: C3
          to: C3R2D
          label: C3R2
      C3R2diode:
        what: f_diode
        where: 
          ref: main_index_bottom
          shift: [-diode_x,-diode_y]
          rotate: 180
        params:
          from: C3R2D
          to: R2
      C4R0:
        what: f_new_choc
        where: 
          ref: main_index2_top          
        params:
          from: C4
          to: C4R0D
          label: C4R0
          hotswap: false
      C4R0diode:
        what: f_diode
        where: 
          ref: main_index2_top
          shift: [diode_x,diode_y]          
        params:
          from: C4R0D
          to: R0
      C4R1:
        what: f_new_choc
        where: 
          ref: main_index2_home          
        params:
          from: C4
          to: C4R1D
          label: C4R1
          hotswap: false
      C4R1diode:
        what: f_diode
        where: 
          ref: main_index2_home
          shift: [diode_x,diode_y]          
        params:
          from: C4R1D
          to: R1          
      C4R2:
        what: f_new_choc
        where: 
          ref: main_index2_bottom
          rotate: 180
        params:
          from: C4
          to: C4R2D
          label: C4R2
      C4R2diode:
        what: f_diode
        where: 
          ref: main_index2_bottom
          shift: [-diode_x,-diode_y]
          rotate: 180
        params:
          from: C4R2D
          to: R2
      rotary:
        what: f_rotary
        where:
          ref: main_pinky_ttop
          shift: [0,0]
          rotate: 90
        params:
          from: C0
          to: C0R3D
          A: P2
          B: P3         
      rotaryDiode:
        what: f_diode
        where: 
          ref: main_pinky_top
          shift: [4,cy+4]
          rotate: 180      
        params:
          from: C0R3D
          to: R3
      slider:
        what: f_slider
        where: 
          ref: main_ring_bottom
          shift: [0, -cy/2+stagger_middle+stagger_index+stagger_index2+slider_offset]
          rotate: 180
        params:          
          one: RAW
          two: BSLI
          three: three
      smdbutton:
        what: f_smdbutton
        where: 
          ref: main_middle_top
          shift: [smdbutton_offset_xR, cy/2+smdbutton_offset_y]
          rotate: 270
        params:          
          one: GND
          two: RST          
      nicenano:
        what: f_nicenano
        where: 
          ref: main_index2_top
          shift: [0, nnano_offset]
          rotate: -90
        params:
          side: B
      batt:
        what: f_jstsh2
        where: 
          ref: main_ring_home
          shift: [0, -5.5]
          rotate: 270
        params:          
          pos: BSLI
          neg: GND
      connector_thumb:
        what: f_jstsh5
        where: 
          ref: main_middle_bottom
          shift: [0, -jst5offset]
          rotate: -90
        params:
          side: B         
      mount_hole1:
        what: f_npth
        where:
          ref: main_pinky_bottom
          shift: [cxR/2,cy/2]
      mount_hole2:
        what: f_npth
        where:
          ref: main_pinky_top
          shift: [cxR/2,cy/2]
      mount_hole3:
        what: f_npth
        where:
          ref: main_middle_bottom
          shift: [-cxR/2,-cy/2]
      mount_hole4:
        what: f_npth
        where:
          ref: main_middle_top
          shift: [-cxR/2,-cy/2]
      mount_hole5:
        what: f_npth
        where:
          ref: main_index_bottom
          shift: [cxR/2,-cy/2]
      mount_hole6:
        what: f_npth
        where:
          ref: main_index_top
          shift: [cxR/2,cy/2-3]
      logo: 
        what: f_text
        where: 
          ref: main_middle_bottom
          shift: [logoxR,-cy/2]          
        params:
          text: "Flactyl 4.0 (left)"
          side: F
          

        
