module.exports = {
    f_slider: require('../../input/flactyl/footprints/slider'),
    f_smdbutton: require('../../input/flactyl/footprints/smdbutton'),
    f_nicenano: require('../../input/flactyl/footprints/nicenano'),
    f_jstsh2: require('../../input/flactyl/footprints/jstsh2'),
    f_jstsh5: require('../../input/flactyl/footprints/jstsh5'),
    f_npth: require('../../input/flactyl/footprints/npth'),
    f_rotary: require('../../input/flactyl/footprints/rotary'),
    f_choc: require('../../input/flactyl/footprints/choc'),
    alps: require('./alps'),
    button: require('./button'),
    choc: require('./choc'),
    chocmini: require('./chocmini'),
    diode: require('./diode'),
    jstph: require('./jstph'),
    jumper: require('./jumper'),
    mx: require('./mx'),
    oled: require('./oled'),
    omron: require('./omron'),
    pad: require('./pad'),
    promicro: require('./promicro'),
    rgb: require('./rgb'),
    rotary: require('./rotary'),
    scrollwheel: require('./scrollwheel'),
    slider: require('./slider'),
    trrs: require('./trrs'),
    via: require('./via'),
}